# Generated by Django 4.2 on 2023-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='Без имени', max_length=40),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cash',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency_unit',
            field=models.CharField(choices=[('RU', 'Рубль'), ('USA', 'Доллар')], default='RU', max_length=3),
        ),
    ]
