# Generated by Django 4.2 on 2023-12-10 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0003_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
