# Generated by Django 4.2 on 2023-12-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0004_wallet_wallet_number_alter_wallet_amount_delete_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='name_card',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
