# Generated by Django 4.2 on 2023-12-13 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0006_alter_creditcard_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RU', 'Рубль'), ('USA', 'Доллар')], default='RU', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('percent', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RU', 'Рубль'), ('USA', 'Доллар')], default='RU', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Applications.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_number',
        ),
        migrations.AddField(
            model_name='wallet',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
