# Generated by Django 4.2 on 2023-12-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_customuser_passport_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditwallet',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='savingswallet',
            old_name='card_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='card_number',
            new_name='number',
        ),
    ]
