# Generated by Django 4.2 on 2023-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_rename_card_number_creditwallet_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='savingswallet',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
