# Generated by Django 4.2 on 2023-12-13 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0010_alter_creditwallet_number_alter_savingswallet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwallet',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='creditwallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
