# Generated by Django 4.2 on 2023-12-15 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0012_alter_creditwallet_amount_alter_customuser_itn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditwallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='savingswallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
